ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  tls:
    - hosts:
        - nextcloud.rarick.me
      secretName: nextcloud-tls

nextcloud:
  host: nextcloud.rarick.me
  username: rarick
  password: ""

persistence:
  enabled: true
  existingClaim: nextcloud-pvc
