apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-cluster-issuer
 namespace: cert-manager
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: tyler.rarick@gmail.com
   privateKeySecretRef:
     name: letsencrypt-cluster-issuer
   solvers:
     - http01:
         ingress:
           class: nginx
